name: Run Feature Pipeline

on:
  push:
    branches:
      - main

jobs:
  feature-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyYAML==6.0 python-dotenv requests pandas numpy

      - name: Create empty __init__.py files
        run: |
          mkdir -p data_collection feature_engineering models evaluation utils
          touch data_collection/__init__.py
          touch feature_engineering/__init__.py
          touch models/__init__.py
          touch evaluation/__init__.py
          touch utils/__init__.py

      - name: Run feature pipeline
        env:
          AQICN_API_KEY: ${{ vars.AQICN_API_KEY }}
          OPENWEATHER_API_KEY: ${{ vars.OPENWEATHER_API_KEY }}
          HOPSWORKS_API_KEY: ${{ vars.HOPSWORKS_API_KEY }}
        run: |
          python feature_pipeline.py
